version: "3"
services:
  log-nginx:
    container_name: log-nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
#      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.default.conf:/etc/nginx/nginx.conf
    networks:
      - log-test

  log-nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: log-nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://host.docker.internal/metrics
    expose:
      - 9113
#    ports:
#      - 9113:9113
    networks:
      - log-test
    depends_on:
      - log-prometheus

  log-test-redis:
    container_name: log-test-redis
    image: redis:6.2.12-alpine
    expose:
      - 6379
    restart: always
    networks:
      - log-test

  log-test-boot:
    container_name: log-test-boot
    image: log-test-boot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs/backend/info:/logs/backend/info
      - ./logs/backend/warn:/logs/backend/warn
      - ./logs/backend/error:/logs/backend/error
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8080:8080
    networks:
      - log-test

  log-grafana:
    container_name: log-grafana
    image: grafana/grafana:latest
    user: "$UID:$GID" # grafana image 내에 /var/lib/grafana의 쓰기작업을 위한 설정
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - log-test

  log-loki:
    container_name: log-loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - log-test

  log-promtail:
    container_name: log-promtail
    image: grafana/promtail:latest
    volumes:
      - ./logs/backend:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - log-test

  log-prometheus:
    container_name: log-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - log-test

networks:
  log-test: