scrape_configs:
  - job_name: 'log-test-boot' # prometheus-boot-actuator
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [host.docker.internal:8080]

  - job_name: 'log-nginx' # prometheus-nginx-exporter
    scrape_interval: 5s
    static_configs:
      - targets: [host.docker.internal:9113]