spring:
  datasource:
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      h2:
        console:
          path: /h2-console
          enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    com.example.logtest: info
    org.hibernate.SQL: debug