spring:
  datasource:
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      h2:
        console:
          path: /h2-console
          enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

server:
  tomcat:
    mbeanregistry:
      enable: true # grafana metric?? ???? ??

logging:
  level:
    org.hibernate.SQL: debug

