spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: log-test-redis # docker container name
#      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

server:
  tomcat:
    mbeanregistry:
      enable: true # grafana metric?? ???? ??

logging:
  level:
    org.hibernate.SQL: debug

